"""
Synthetic Markov-chain text corpus for the 10M-scale validation.

WHY SYNTHETIC:
- No internet access in this environment, so we can't download a real
  text dataset (WikiText, OpenWebText, etc.).
- A synthetic Markov chain gives us:
  * Deterministic (seeded) → reproducible across runs
  * Non-trivial entropy (bigram statistics) → model must learn structure
  * Controllable vocab/distribution → fair across all 4 configs
  * Unlimited tokens → can train as long as budget allows

The corpus is generated by:
  1. Sample unigram frequencies from a Zipf distribution (vocab=10000)
  2. Sample bigram transition matrix with structure (clusters of words
     that transition to each other — simulates topics/syntax)
  3. Generate sequences by sampling from the bigram model

This gives realistic per-token entropy (~6-8 bits) — comparable to
simple English text. A model that learns the bigram structure should
achieve val loss << log(10000) = 9.21.
"""
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader


class MarkovCorpus:
    """
    Deterministic Markov-chain corpus.

    Vocab: 10000 tokens (0..9999). Token 0 = PAD.
    Structure: 50 "topic clusters" of 200 words each. Within a cluster,
    bigram transition probability is high; across clusters, low. This
    simulates coherent text where words from the same topic co-occur.
    """
    def __init__(self, vocab_size=10000, num_clusters=50, seed=42):
        self.vocab_size = vocab_size
        self.num_clusters = num_clusters
        self.seed = seed
        rng = np.random.RandomState(seed)

        # Assign each token to a cluster (round-robin)
        self.cluster_of = np.array([t % num_clusters for t in range(vocab_size)])

        # Build bigram transition matrix: P(next | current)
        # Within-cluster: high probability (concentrated on a few words)
        # Cross-cluster: low probability (uniform-ish)
        # We use a sparse representation: for each token, store top-K
        # next-token candidates with their probabilities.
        self.top_k = 50  # sparsity of bigram
        # For each token, sample top_k next-token indices and probabilities
        self.next_indices = np.zeros((vocab_size, self.top_k), dtype=np.int64)
        self.next_probs = np.zeros((vocab_size, self.top_k), dtype=np.float32)
        for t in range(vocab_size):
            c = self.cluster_of[t]
            # 80% of candidates from same cluster, 20% from random
            n_same = int(self.top_k * 0.8)
            same_pool = np.where(self.cluster_of == c)[0]
            same_pool = same_pool[same_pool != t]  # exclude self
            if len(same_pool) >= n_same:
                same_candidates = rng.choice(same_pool, n_same, replace=False)
            else:
                same_candidates = rng.choice(same_pool, n_same, replace=True)
            n_other = self.top_k - n_same
            other_candidates = rng.choice(vocab_size, n_other, replace=False)
            candidates = np.concatenate([same_candidates, other_candidates])
            # Probabilities: Zipf-like (concentrated)
            raw = rng.zipf(2.0, size=self.top_k).astype(np.float32)
            raw = raw / raw.sum()
            # Shuffle so the order isn't correlated with cluster
            rng.shuffle(raw)
            self.next_indices[t] = candidates
            self.next_probs[t] = raw

        # Compute per-token entropy (for sanity check).
        # Each row of next_probs is a distribution over top_k candidates.
        # The entropy of EACH row tells us how predictable the next token is
        # given the current token. We average across all tokens.
        self.token_entropy = -np.sum(
            self.next_probs * np.log2(self.next_probs + 1e-12), axis=1
        )  # [vocab_size] — entropy per token, in bits
        # Average per-token entropy (bits) → minimum achievable loss in nats
        # = mean_entropy_bits * ln(2)
        self.mean_entropy_bits = float(np.mean(self.token_entropy))
        self.min_loss_nats = self.mean_entropy_bits * np.log(2)

    def sample_sequence(self, length, rng):
        """Sample a sequence of given length from the Markov chain."""
        seq = np.zeros(length, dtype=np.int64)
        # Start with a random non-PAD token
        seq[0] = rng.randint(1, self.vocab_size)
        for i in range(1, length):
            prev = seq[i-1]
            # With probability 0.95, follow the bigram
            if rng.random() < 0.95:
                idx = rng.choice(self.top_k, p=self.next_probs[prev])
                seq[i] = self.next_indices[prev, idx]
            else:
                # 5% chance of a random token (noise)
                seq[i] = rng.randint(1, self.vocab_size)
        return seq

    def generate_dataset(self, n_sequences, seq_length, seed=None):
        """Generate a dataset of n_sequences each of length seq_length."""
        rng = np.random.RandomState(seed if seed is not None else self.seed + 1)
        data = np.zeros((n_sequences, seq_length), dtype=np.int64)
        for i in range(n_sequences):
            data[i] = self.sample_sequence(seq_length, rng)
        return data


class MarkovDataset(Dataset):
    """torch Dataset wrapper around a Markov corpus."""
    def __init__(self, data):
        self.data = torch.from_numpy(data).long()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


def build_markov_dataloaders(vocab_size=10000, seq_length=128,
                              train_sequences=4000, val_sequences=400,
                              batch_size=8, seed=42):
    """Build train + val DataLoaders from the Markov corpus."""
    corpus = MarkovCorpus(vocab_size=vocab_size, seed=seed)
    train_data = corpus.generate_dataset(train_sequences, seq_length, seed=seed+1)
    val_data = corpus.generate_dataset(val_sequences, seq_length, seed=seed+2)
    train_ds = MarkovDataset(train_data)
    val_ds = MarkovDataset(val_data)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, drop_last=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, drop_last=False)
    return corpus, train_loader, val_loader


if __name__ == "__main__":
    # Sanity check
    corpus, train_loader, val_loader = build_markov_dataloaders(
        vocab_size=10000, seq_length=128, train_sequences=100, val_sequences=20,
        batch_size=4, seed=42,
    )
    print(f"Markov corpus:")
    print(f"  vocab_size: {corpus.vocab_size}")
    print(f"  num_clusters: {corpus.num_clusters}")
    print(f"  mean per-token entropy: {corpus.mean_entropy_bits:.3f} bits")
    print(f"  theoretical min loss (nats): {corpus.min_loss_nats:.4f}")
    print(f"  log(vocab) = {np.log(corpus.vocab_size):.4f} (uniform baseline)")
    print(f"\nTrain: {len(train_loader)} batches × {train_loader.batch_size} = "
          f"{len(train_loader.dataset)} sequences")
    print(f"Val:   {len(val_loader)} batches × {val_loader.batch_size} = "
          f"{len(val_loader.dataset)} sequences")
    # Sample batch
    for batch in train_loader:
        print(f"\nSample batch shape: {batch.shape}")
        print(f"First sequence (first 20 tokens): {batch[0, :20].tolist()}")
        break
